create table ES_YDENPYO (
DENPYONO  number primary key not null ,
KAIKEIND  number,							
UKETUKEDT varchar2(30),		
DENPYODT varchar2(30),										
BUMONCD_YKANR varchar2(30),
BIKO varchar2(30),
SUITOKB	varchar2(30),		
SHIHARAIDT varchar2(30),
KINGAKU	number,
INSERT_OPE_ID varchar2(30),
INSERT_PGM_ID varchar2(30) default 'AWCYO26001',
INSERT_PGM_PRM	varchar2(30) default '00000' ,
INSERT_DATE	varchar2(30),
UPDATE_OPE_ID varchar2(30),
UPDATE_PGM_ID varchar2(30) default 'AWCYO26001',
UPDATE_PGM_PRM varchar2(30) default '00000',
UPDATE_DATE	varchar2(30)
);

CREATE TABLE ES_YDENPYOD (
    
    GYONO              NUMBER(5)        NOT NULL,
    DENPYONO           NUMBER(10)       NOT NULL,
    
    IDODT              DATE, 
    
    SHUPPATSUPLC       VARCHAR2(100),
    MOKUTEKIPLC        VARCHAR2(100),
    KEIRO              VARCHAR2(200),
    KINGAKU            NUMBER(12,2),
    
    INSERT_OPE_ID      VARCHAR2(30),
    INSERT_PGM_ID      VARCHAR2(20),
    INSERT_PGM_PRM     VARCHAR2(20),
    INSERT_DATE        DATE,
    
    UPDATE_OPE_ID      VARCHAR2(30),
    UPDATE_PGM_ID      VARCHAR2(20),
    UPDATE_PGM_PRM     VARCHAR2(20),
    UPDATE_DATE        DATE,

    CONSTRAINT PK_KOTSUHI_MEISAI
        PRIMARY KEY (DENPYONO, GYONO),

    CONSTRAINT FK_KOTSUHI_DENPYO
        FOREIGN KEY (DENPYONO)
        REFERENCES ES_YDENPYO (DENPYONO)
);

CREATE OR REPLACE TRIGGER TRG_UPDATE_DENPYO_KINGAKU
AFTER INSERT OR UPDATE OR DELETE
ON ES_YDENPYOD
DECLARE
BEGIN

    UPDATE ES_YDENPYO p
    SET p.KINGAKU =
    (
        SELECT NVL(SUM(d.KINGAKU),0)
        FROM ES_YDENPYOD d
        WHERE d.DENPYONO = p.DENPYONO
    )
    WHERE EXISTS
    (
        SELECT 1
        FROM ES_YDENPYOD d
        WHERE d.DENPYONO = p.DENPYONO
    );

END;
/


